# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='server_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='view_table_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansi_view_table_name', models.CharField(max_length=100)),
                ('pretty_view_table_name', models.CharField(max_length=100)),
                ('database_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SqlProfiles.database_info')),
            ],
        ),
        migrations.CreateModel(
            name='view_table_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_date', models.DateTimeField(verbose_name='date this record was created')),
                ('view_table_row_count', models.IntegerField()),
                ('view_table_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SqlProfiles.view_table_info')),
            ],
        ),
        migrations.AddField(
            model_name='database_info',
            name='server_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SqlProfiles.server_info'),
        ),
    ]
