# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_table_profile',
            name='i_finally_got_it_working',
            field=models.IntegerField(default=123),
        ),
    ]
