# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlProfiles', '0002_view_table_profile_i_finally_got_it_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnHistogram',
            fields=[
                ('column_histogram_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_profile_id', models.IntegerField()),
                ('column_info_id', models.IntegerField()),
                ('column_value_count', models.IntegerField(blank=True, null=True)),
                ('column_value_string', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'column_histogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnInfo',
            fields=[
                ('column_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('ansi_full_column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ansi_full_table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'column_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnProfile',
            fields=[
                ('column_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_info_id', models.IntegerField()),
                ('column_distinct_count', models.IntegerField(blank=True, null=True)),
                ('column_distinct_count_execution_seconds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('column_distinct_count_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'column_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('database_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('database_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'database_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('server_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=100)),
                ('server_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'server_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('ansi_full_table_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logical_path', models.CharField(blank=True, max_length=100, null=True)),
                ('table_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableProfile',
            fields=[
                ('table_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_row_count', models.IntegerField(blank=True, null=True)),
                ('table_row_count_datetime', models.DateTimeField(blank=True, null=True)),
                ('table_row_count_execution_seconds', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'table_profile',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='database_info',
            name='server_info',
        ),
        migrations.RemoveField(
            model_name='view_table_info',
            name='database_info',
        ),
        migrations.RemoveField(
            model_name='view_table_profile',
            name='view_table_info',
        ),
        migrations.DeleteModel(
            name='database_info',
        ),
        migrations.DeleteModel(
            name='server_info',
        ),
        migrations.DeleteModel(
            name='view_table_info',
        ),
        migrations.DeleteModel(
            name='view_table_profile',
        ),
    ]
