# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('DatabaseInfoID', models.AutoField(primary_key=True, serialize=False)),
                ('DatabaseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('ServerInfoID', models.AutoField(primary_key=True, serialize=False)),
                ('ServerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='ServerInfoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SqlProfiles.ServerInfo'),
        ),
    ]
