# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableViewInfo',
            fields=[
                ('TableViewInfoID', models.AutoField(primary_key=True, serialize=False)),
                ('TableViewInfoName', models.CharField(max_length=100)),
                ('DatabaseInfoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SqlProfiles.DatabaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TableViewProfile',
            fields=[
                ('TableViewProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('TableViewProfileDate', models.DateTimeField(verbose_name='date this record was created')),
                ('RowCount', models.IntegerField()),
            ],
        ),
    ]
